config/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from rest_framework.authtoken import views

# In the future, (v1|v2) etc.
API_URL_ROOT = r"api/(?P<version>(v1))/"

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("django_starter_peter.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("artists/", include("artists.urls")),
    path("api-auth/", include("rest_framework.urls")),
    # re_path(API_URL_ROOT, include('config.api_urls')),
    re_path(API_URL_ROOT + "artists/", include("artists.api_urls")),
    re_path(API_URL_ROOT + "get-auth-token/", views.obtain_auth_token),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")},),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/", default_views.page_not_found, kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

django_starter_peter/users/urls.py
from django.urls import path

from django_starter_peter.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

artists/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


class Artist(models.Model):

    ARTIST_TYPE_NONE = "None"
    ARTIST_TYPE_ARTIST = "Artist"
    ARTIST_TYPE_COMMISSIONED_ARTIST = "Commissioned"
    ARTIST_TYPE_WORKSHOP_PARTICIPANT = "Storyteller"
    ROLE_CHOICES = [
        (ARTIST_TYPE_NONE, "None"),
        (ARTIST_TYPE_ARTIST, "Artist"),
        (ARTIST_TYPE_COMMISSIONED_ARTIST, "Commissioned Artist"),
        (ARTIST_TYPE_WORKSHOP_PARTICIPANT, "Storyteller"),
    ]

    name = models.CharField("Artist Name", max_length=200)
    bio = models.TextField("Artist Bio", blank=True, max_length=5000)
    role = models.CharField(
        "Artist Type", choices=ROLE_CHOICES, default=ARTIST_TYPE_ARTIST, max_length=20
    )

    public_url = models.CharField("Artist Website", blank=True, max_length=500)
    public_twitter = models.CharField("Artist Twitter", blank=True, max_length=500)
    public_instagram = models.CharField("Artist Instagram", blank=True, max_length=500)

    private_email = models.CharField(
        "Contact Email (private)", blank=True, max_length=100
    )
    private_phone = models.CharField(
        "Contact Phone (private)", blank=True, max_length=100
    )

    # Tracking fields
    creation_date = models.DateTimeField(default=timezone.now)
    creation_user = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="artist_creation_user", null=True
    )
    modification_date = models.DateTimeField(default=timezone.now)
    modification_user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="artist_modification_user",
        null=True,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("artist-detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):  # pylint: disable=arguments-differ
        """ On save, update timestamps """
        if not self.id:
            self.creation_date = timezone.now()
        self.modification_date = timezone.now()
        return super(Artist, self).save(*args, **kwargs)

django_starter_peter/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

# Grant a token to every user, for API-use
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

django_starter_peter/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

django_starter_peter/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

django_starter_peter/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Django Starter Peter{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.png' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

    <!-- Le javascript
    ================================================== -->
    <!-- Moved to the top because some widgets need jQuery
    (was: Placed at the end of the document so the pages load faster) -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Django Starter Peter</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
              {% if perms.artists.view_artist %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path|slice:9 == '/artists/' %}active{% endif %}"
                      href="{% url 'artists-list' %}">{% trans "Artists" %}</a>
                </li>
              {% endif %}
            {% endif %}
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link {% if request.path|slice:7 == '/users/' %}active{% endif %}"
                  href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

  </body>
</html>
 

django_starter_peter/templates/filterablelist.html
<script>
    function filter_and_refresh(clear) {
        var filter = document.getElementById("searchbox").value
        if (clear) { filter = "" }
        window.location.href = "{% url request.resolver_match.url_name %}?filter=" + filter
    }
    function filter_keyup(event) {
        if (event.key == 'Enter') {
            filter_and_refresh(false)
        }
    }
</script>

<span class="ml-4 text-muted btn btn-sm" disabled="True">Search:</span>

<input class="form-control form-control-sm" id="searchbox" type="text" onkeyup="filter_keyup(event)" value="{{filter}}" placeholder="Search by title">

<button class="btn btn-outline-info btn-sm ml-1" id="searchbutton" onclick="filter_and_refresh(false)">Search</button>

{% if objects.count == unfiltered_count %}
    <span class="btn btn-sm">({{unfiltered_count}} {{objectname}}{{unfiltered_count|pluralize}})</span>
{% else %}
    <button class="btn btn-info btn-sm ml-1" id="searchbutton" onclick="filter_and_refresh(true)">Clear</button>
    <span class="btn btn-sm">(matches {{objects.count}} of {{unfiltered_count}} {{objectname}}{{unfiltered_count|pluralize}})</span>
{% endif %}

django_starter_peter/templates/paginator.html
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-sm btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-sm btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">←</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-sm btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-sm btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-sm btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">→</a>
            <a class="btn btn-sm btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}

django_starter_peter/templates/sortablelist.html
<span class="text-muted btn btn-sm" disabled="True">Sort:</span>
{% if sort == 'name' %}
    <a class="btn btn-light btn-sm" href="{% url request.resolver_match.url_name %}?sort=-name">Name&nbsp;▲</a>
{% elif sort == '-name' %}
    <a class="btn btn-light btn-sm" href="{% url request.resolver_match.url_name %}?sort=name">Name&nbsp;▼</a>
{% else %}
    <a class="btn btn-light btn-sm" href="{% url request.resolver_match.url_name %}?sort=name">Name</a>
{% endif %}

{% if sort == 'modification_date' %}
    <a class="btn btn-light btn-sm ml-2" href="{% url request.resolver_match.url_name %}?sort=-modification_date">Last Modified&nbsp;▲</a>
{% elif sort == '-modification_date' %}
    <a class="btn btn-light btn-sm ml-2" href="{% url request.resolver_match.url_name %}?sort=modification_date">Last Modified&nbsp;▼</a>        
{% else %}
    <a class="btn btn-light btn-sm ml-2" href="{% url request.resolver_match.url_name %}?sort=-modification_date">Last Modified</a>
{% endif %}